import 'package:finacct/common/commonforall.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [Component3()])),
    );
  }
}

class Component3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Commonforall(),
        Container(
          width: 413,
          height: 920,
          child: Stack(
            children: [
              Positioned(
                left: 46,
                top: 224,
                child: Container(
                  width: 296.83,
                  height: 26,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFE7E7E7),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(5),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 279,
                        top: 5,
                        child: Container(
                          width: 14,
                          height: 14,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 353.24,
                top: 224,
                child: Container(
                  width: 29.76,
                  height: 26,
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0x357A8380),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(5),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                  ),
                ),
              ),
              Positioned(
                left: 124,
                top: 78,
                child: Container(
                  width: 153,
                  height: 44.16,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/153x44"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 111.70,
                top: 59.70,
                child: Container(
                  width: 170.04,
                  height: 90.54,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 170.04,
                          height: 90.54,
                          decoration: BoxDecoration(
                            color: const Color(0xFF23538D),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 61.30,
                        top: 46.30,
                        child: Container(
                          width: 104,
                          height: 12,
                          decoration: BoxDecoration(color: Colors.black),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 272,
                child: Container(
                  width: 359,
                  height: 613,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFC2DDFF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 32,
                top: 272,
                child: Container(
                  width: 359,
                  height: 613,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFC2DDFF),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(20),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 54,
                top: 306,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    'Aichik Bachat Khata',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 221,
                top: 306,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '0102ABK-11-000577-1',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 50,
                top: 504,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '2080-04-05',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 658,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '2080-04-05',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 680,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '2080-04-05',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 46,
                top: 588,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '50000',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 221,
                top: 595,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '10000.0',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 221,
                top: 418,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '200.0',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 46,
                top: 612,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '50000',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 221,
                top: 504,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '2081-04-05',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 48,
                top: 526,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '2080-06-09',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 221,
                top: 526,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '2081-06-09',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 221,
                top: 330,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '0102RBK-11-003477-1',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 117,
                top: 890,
                child: Text(
                  ' Info brain technologies Pvt. Ltd.',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFF23538D),
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 55,
                top: 357,
                child: Container(
                  width: 298,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 57,
                top: 787,
                child: Container(
                  width: 298,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 57,
                top: 560,
                child: Container(
                  width: 298,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 57,
                top: 470,
                child: Container(
                  width: 298,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 96,
                top: 284,
                child: SizedBox(
                  width: 51,
                  height: 11,
                  child: Text(
                    'AC TYPES',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 64,
                top: 370,
                child: SizedBox(
                  width: 116,
                  height: 11,
                  child: Text(
                    'INPUT AMOUNT(NRS)',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 269,
                top: 284,
                child: SizedBox(
                  width: 51,
                  height: 11,
                  child: Text(
                    'ACCOUNT',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 96,
                top: 568,
                child: SizedBox(
                  width: 51,
                  height: 11,
                  child: Text(
                    'BALANCE',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 80,
                top: 639,
                child: SizedBox(
                  width: 84,
                  height: 11,
                  child: Text(
                    'BALANCE DATE',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 269,
                top: 370,
                child: SizedBox(
                  width: 51,
                  height: 11,
                  child: Text(
                    'TOTAL',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 269,
                top: 568,
                child: SizedBox(
                  width: 51,
                  height: 11,
                  child: Text(
                    'TOTAL',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 64,
                top: 482,
                child: SizedBox(
                  width: 116,
                  height: 11,
                  child: Text(
                    'ACCOUNT OPEN DATE',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 237,
                top: 482,
                child: SizedBox(
                  width: 116,
                  height: 11,
                  child: Text(
                    'MATURITY DATE',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 47,
                top: 331,
                child: SizedBox(
                  width: 155,
                  height: 12,
                  child: Text(
                    '10 Years Dobbar Bachat',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 64,
                top: 397,
                child: Container(
                  width: 116,
                  height: 23,
                  padding: const EdgeInsets.only(
                    top: 20,
                    left: 20,
                    right: 35,
                    bottom: 20,
                  ),
                  decoration: ShapeDecoration(
                    color: const Color(0xFFF1F4FF),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 2),
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                  ),
                ),
              ),
              Positioned(
                left: 67,
                top: 432,
                child: Container(
                  width: 113,
                  height: 23,
                  padding: const EdgeInsets.only(
                    top: 20,
                    left: 20,
                    right: 35,
                    bottom: 20,
                  ),
                  decoration: ShapeDecoration(
                    color: const Color(0xFFF1F4FF),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(width: 2),
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                  ),
                ),
              ),
              Positioned(
                left: 67,
                top: 401,
                child: SizedBox(
                  width: 110,
                  height: 15,
                  child: Text(
                    '100',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 67,
                top: 436,
                child: SizedBox(
                  width: 110,
                  height: 15,
                  child: Text(
                    '100',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 11,
                top: 227,
                child: Container(
                  width: 21,
                  height: 21,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/21x21"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 1,
                top: 0,
                child: Container(
                  width: 412,
                  height: 49,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 2,
                        top: 13,
                        child: SizedBox(
                          width: 54,
                          child: Text(
                            '9:41',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                              fontFamily: 'SF Pro Text',
                              fontWeight: FontWeight.w600,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 373.33,
                        top: 20.33,
                        child: Opacity(
                          opacity: 0.35,
                          child: Container(
                            width: 22,
                            height: 11.33,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(width: 1, color: Colors.white),
                                borderRadius: BorderRadius.circular(2.67),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 375.33,
                        top: 22.33,
                        child: Container(
                          width: 18,
                          height: 7.33,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1.33),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 883,
                child: Container(
                  width: 412,
                  height: 37,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 139,
                        top: 24,
                        child: Container(
                          width: 134,
                          height: 5,
                          decoration: ShapeDecoration(
                            color: const Color(0x7FC2DDFF),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 46,
                top: 742,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '50',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 46,
                top: 815,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '500',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 52,
                top: 858,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '2081-04-15',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 221,
                top: 816,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '500',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 221,
                top: 742,
                child: SizedBox(
                  width: 148,
                  height: 12,
                  child: Text(
                    '50',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w300,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 77,
                top: 720,
                child: SizedBox(
                  width: 111,
                  height: 11,
                  child: Text(
                    'INST AMOUNT(NRS)',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 77,
                top: 797,
                child: SizedBox(
                  width: 111,
                  height: 11,
                  child: Text(
                    'DUE AMOUNT(NRS)',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 838,
                child: SizedBox(
                  width: 111,
                  height: 11,
                  child: Text(
                    'PB CHECK DATE',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 269,
                top: 720,
                child: SizedBox(
                  width: 51,
                  height: 11,
                  child: Text(
                    'TOTAL',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 269,
                top: 797,
                child: SizedBox(
                  width: 51,
                  height: 11,
                  child: Text(
                    'TOTAL',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 10,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
